### ISSUE TITLE
Default setup should work without `x-forwarded-prefix`

### ISSUE THREAD

**Issue by yu-re-ka** [envelope-zero/backend#163]
If the reverse-proxy forwards /api/ to the backend http://127.0.0.1:8080/, it currently requires the `x-forwarded-prefix` header to be set, otherwise the backend will return the endpoints without /api/.

**Comment by morremeyer** [comment]
With #166, the backend will detect the use of a reverse proxy by checking for the `x-forwarded-host` header. 

If it is set, `/api` is used by default. If the `x-forwarded-prefix` header is set, it is used instead.

**Comment by morremeyer** [comment]
This is included in `v0.21.0`
