### ISSUE TITLE
Group Envelopes by Category for /v1/budgets/{budgetId}/{month}

### ISSUE THREAD

**Issue by malfynnction** [envelope-zero/backend#358]
The `/v1/budgets/{budgetId}/{month}` endpoint currently includes a flat array of envelopes with info on their allocation, spent, and balance.
Imo it would make more sense to group them by category to avoid having to make additional request if you want to display them grouped

**Comment by morremeyer** [comment]
This would be a breaking change to the current endpoint, requiring API v2. As I've never been too happy with the path for the month endpoints anyway, I'm proposing the following change:

* Add a `/v1/month?budget={budgetId}&month={month}` endpoint with the following verbs:
  * `GET`: Get the budget month calculations like the current `/v1/budgets/{budgetId}/{month}` endpoint, but with envelopes grouped by category (detailed response format see below) 
  * `POST`: Set the allocations for a month (deprecates the current `POST /v1/budgets/{budgetId}/{month}/allocations` without changing the semantics of the endpoint)
  * `DELETE`: Delete all allocations for this month (deprecates the current `POST /v1/budgets/{budgetId}/{month}/allocations` without changing the semantics of the endpoint)

This endpoint would return the following format on `GET` requests:

```
{
  "data": {
    "available": 217.34,
    "budgeted": 2100,
    "id": "1e777d24-3f5b-4c43-8000-04f65f895578",
    "income": 2317.34,
    "month": "2006-05-01T00:00:00.000000Z",
    "name": "Envelope Zero Demo Budget",
    "categories": [
      {
        "id": "52d967d3-33f4-4b04-9ba7-772e5ab9d0ce",
        "name": "Groceries",
        "envelopes": [
          {
            "allocation": 85.44,
            "balance": 12.32,
            "id": "10b9705d-3356-459e-9d5a-28d42a6c4547",
            "name": "Groceries",
            "spent": 73.12
          }
        ]
      }
    ]
  }
}
```

@malfynnction, what do you think?
