### ISSUE TITLE
Available to budget calculation is *wildly* off

### ISSUE THREAD

**Issue by morremeyer** [envelope-zero/backend#413]
**Describe the bug**
The calculation of the sum available to budget is wildly off. It apparently factors in deleted transactions and transactions from deleted budgets as well.

**To Reproduce**

1. Create an income transaction for 1000
2. See that the „available to budget“ is 1000 greater than before
3. Delete the transaction
4. See that the „available to budget“ hasn't changed

**Expected behavior**
Only existing transactions for the budget I'm currently requesting data for should be factored in

**Comment by Alig1493** [comment]
Is this issue more or less done? IS the project accepting external PRs?

**Comment by morremeyer** [comment]
@Alig1493 I haven't started working on this specific issue yet.

And yes, the project is accepting external PRs! We're happy about anybody willing to contribute.
