### ISSUE TITLE
Exclude hidden resources from list responses

### ISSUE THREAD

**Issue by malfynnction** [envelope-zero/backend#532]
> Do not show resources that have the hidden attribute set to true in lists.

(https://github.com/envelope-zero/frontend/issues/533)

This should be handled by the backend directly – hidden (archived) resources should only be included in the list response if explicitly requested (eg by setting a filter param)

**Comment by morremeyer** [comment]
As discussed: The backend doesn't care about the hidden state of a resource. It's just a flag. For that reason, we'll not change the default, but add a filter for `hidden` on all resources that have the flag.
