### ISSUE TITLE
Transaction Filter "Direction"

### ISSUE THREAD

**Issue by malfynnction** [envelope-zero/backend#565]
It would be nice to add a filter parameter `direction` to the transaction list.
It could have the following values:
- "incoming": off-budget account -> on-budget account
- "outgoing": on-budget account -> off-budget account
- "transfer": internal account -> internal account

**Comment by morremeyer** [comment]
This is kind of related to https://github.com/envelope-zero/frontend/issues/618.

We need to clearly define what we see as a **transfer**: Either

* a transaction with source and destination account being on-budget, or
* a transaction with source and destination account being internal

**Comment by morremeyer** [comment]
I'll implement this as initially proposed by @malfynnction.
If we find out that it doesn't work well, we can iterate on it.
