### ISSUE TITLE
Disclosing import match rules

### ISSUE THREAD

**Issue by fhreichert** [envelope-zero/backend#738]
**Is your feature request related to a problem? Please describe.**
When importing, great care is needed to prevent duplicate external accounts.

**Describe the solution you'd like**
An indication that allows me to identify if an imported transaction account has been matched (either by exact matching or replacement rule. Ideally, there is sufficient information for the type of match and the match rule, to discern, how the match was made)

**Comment by morremeyer** [comment]
The backend portion of this is implemented in https://github.com/envelope-zero/backend/pull/737, I created a follow-up issue in the frontend: https://github.com/envelope-zero/frontend/issues/1023

Please watch the frontend issue for further updates.
